### ISSUE TITLE
[Proposal] Promote and/or document the use of the Tunnel CRD

### ISSUE THREAD

**Issue by jsiebens** [inlets/inlets-operator#104]
Some people reported to have issues when running the inlets-operator in combination with another LoadBalancer controller like MetalB. When having multiple LoadBalancer present at the same time, whenever a Service type LoadBalancer is created, BOTH LBs will provide an address.

Although the inlets-operator has a flag `-annotated-only`, must other LoadBalancer controller do not have such kind of feature and will compete with the inlets-operator.

The inlets-operator can also create the required exit-node and client deployment without the need of a LoadBalancer service, but by creating a Tunnel resource. This is not really documented and can be a proper solution when running together with other LoadBalancer controllers.

E.g:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: inlets.inlets.dev/v1alpha1
kind: Tunnel
metadata:
  name: nginx
spec:
  serviceName: nginx
  auth_token: <token>
```

## Expected Behaviour

The inlets-operator can be deployed together with other LoadBalancer controllers without having them compete against each other.

## Current Behaviour

When having multiple LoadBalancer present, both will provide an address for each Service of type LoadBalancer

## Possible Solution

Promote and document the usage of Tunnel resource in combination with the `annotated-only` flag
Optional: change the current behaviour by making the `-annotated-flag` to `true` by default

## Steps to Reproduce (for bugs)

1. install inlets-operator and MetalB
2. create a service of type LoadBalancer
3. both controllers will act on the created service

## Context

Related issues:

https://github.com/inlets/inlets-operator/issues/95
https://github.com/kubernetes/kubernetes/issues/91306
https://github.com/metallb/metallb/issues/685

## Your Environment

* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:

* Kubernetes version `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):

* Cloud provisioner: (DigitalOcean.com / Packet.com / etc)
