### ISSUE TITLE
[BUG][GCE] Missing ports

### ISSUE THREAD

**Issue by angelbarrera92** [inlets/inlets-operator#46]
Using GCE as provider in inlets-operator while creating a service type load-balancer with the following specification:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-controller
  name: ingress-controller
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-controller
  type: LoadBalancer
```

The firewall rule does not open port 80 nor 443. It's open only the 8080 port.

## Expected Behaviour

All ports defined in the LoadBalancer service has to be opened in the firewall-rule

## Current Behaviour

The operator just open the 8080 port:

https://github.com/inlets/inlets-operator/blob/master/controller.go#L494

## Possible Solution

The `firewall-port` should accept an array of ports.

## Steps to Reproduce (for bugs)

Deploy gce inlets-operator. 
Follow the getting started in this repo: https://github.com/inlets/inlets-operator#get-a-loadbalancer-provided-by-inlets

## Context

I am trying to create an exit node to serve as loadbalancer for my ingress controller. (Nginx Ingress Controller)

## Your Environment

* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`
Latest

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:
GKE 1.15.4

* Kubernetes version `kubectl version`:
1.17.1

* Operating System and version (e.g. Linux, Windows, MacOS):
COS

* Cloud provisioner: (DigitalOcean.com / Packet.com / etc)

Google Cloud

**Comment by utsavanand2** [comment]
Hi @angelbarrera92 
Thanks for the feedback. I see your problem and I'll try to reproduce it. I'm having trouble in tracking the changes which is leading to a behavior where the firewall ports do not open due to the lack of appropriate IAM roles, if you look at the logs of inlets-operator. But earlier all of the changes were rigorously tested and then merged. So it is either with the client libraries, or something with IAM roles that have changed. I'll also thoroughly look through the code again just to make sure.
As far as the possible solution you're suggesting, the http and https ports are something which is common and should be opened by default on inlets-operator to avoid any confusion by the tinkerers and maintainers of the code. So I abstracted it away from the inlets-operator code so it is specific about what inlets control port we want to open and leave the http port 80 and https ports 443 to the provisioner. As you can see in this snippet [here](https://github.com/inlets/inletsctl/blob/3f1c896a5ac31d0ee7651a8074fc687e7f0c27ff/pkg/provision/gce.go#L65).
So, if you not having or accidentally deleted the firewall rules (present by default in every GCP project) which targets instances with tags: http-server, and https-server, then this can be the reason for your issue too. Let me know if you have these rules up with the correct target tags 😄

**Comment by angelbarrera92** [comment]
I don't think is lack permission problem. I saw the code and it does not "forward" service ports to the cloud provider requests... the 8080 port it's hardcoded.

About the tagging `http-server` and `https-server`... What if my app is exposed at port 3000?

I think is a good idea to open service ports in the exit node firewall.

**Comment by alexellis** [comment]
For the free version of inlets we use port 8080 for control and 80 for the data, so your internal port of 3000 will be available as port 80 on the public node. 

For 1:1 port mapping you need to use inlets-pro.

It sounds like good isn't a bug then and we can close the issue? Feel free to apply for a free trial of inlets-pro.

**Comment by angelbarrera92** [comment]
Hi @alexellis, this behavior is not what i saw in my cluster.

If I've understood what you said, if i create a service like this one:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  ports:
  - name: my-port
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-app
  type: LoadBalancer
```

I should be able to access `my-app` with the inlets exit node IP. Am I right?

That's not what I saw in my cluster... The only open port in the inlets exit node is the 8080 port.

Thanks!
