### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by StoicPerlman** [inlets/inlets-operator#59]
## Expected Behaviour
I am unable to access https content through the proxy. Does this support https proxying? I didn't think this was a inlets-pro feature, but if so that would answer my questions.

This could be a misunderstanding on how inlets/inlet-operator works on my part so clarification would be great.

## Current Behaviour
I have a k3s cluster configured with Traefik, cert-manager, and metal-lb. I used inlets to allow access into the cluster so cert-manager could use http01 to issue the ssl cert. Now if my local DNS is pointing to the the local IP (issued by metal-lb) of Traefik LoadBalancer I am able to see the site with a valid LetsEncrypt cert.

For external access I set my DNS provider to point to the IP of the inlets-tunnel on digital ocean. I am able to access the site using http, but not https.

## Possible Solution
Document the process for configuring LoadBalancers for https access.

### 2. Use helm 3 to update k3s Traefik to enable ssl.
```
helm upgrade --reuse-values -f values.yaml -n kube-system traefik stable/traefik
```
```
# Traefik values.yaml
externalTrafficPolicy: Local
dashboard:
  enabled: true
  domain: traefik.local.lan
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/whitelist-source-range: "192.168.1.0/24,127.0.0.0/8,::1/128"
ssl:
  enabled: true
  generateTLS: true
```
### 3. Install metal-lb using helm 3
```
kubectl create namespace metallb-system
helm install metallb stable/metallb --namespace metallb-system -f values.yml
```
```
# metal-lb values.yaml
configInline:
  address-pools:
    - name: default-ip-space
      protocol: layer2
      addresses:
        - 192.168.1.60-192.168.1.99
```

### 4. Install cert manager
Excluding config for brevity but the cert is issued successfully. 

### 5. Install inlets using helm 3
```
helm repo add inlets https://inlets.github.io/inlets-operator/
helm repo update
kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/master/artifacts/crd.yaml
kubectl create ns inlets
kubectl create secret -n inlets generic inlets-access-key \
    --from-literal inlets-access-key="CHANGEME"
helm install inlets-operator inlets/inlets-operator --namespace inlets -f values.yaml
```
```
# inlets values.yaml
provider: "digitalocean"
region: "nyc1"
```
### 6. Deploy an arm version of httpbin for testing.
```
# httpbin service.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpbin
  namespace: httpbin
  annotations:
    kubernetes.io/ingress.class: traefik
    # ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: httpbin-tls-cert
      hosts:
        - httpbin.mydomain.com
  rules:
    - host: httpbin.local.lan
      http:
        paths:
          - backend:
              serviceName: httpbin
              servicePort: 80
    - host: httpbin.mydomain.com
      http:
        paths:
          - backend:
              serviceName: httpbin
              servicePort: 80
```
### 7. Configure DNS
- Configure local DNS to point to metal-lb IP. httpbin.local.lan -> 192.168.1.60, httpbin.mydomain.com -> 192.168.1.60
- Configure DNS provider (google domains) to point to digital ocean. httpbin.mydomain.com -> xxx.xxx.xxx.xxx

## Context
I am trying to enable secure access to services within my cluster. I am mainly looking to safely expose [home assistant](https://www.home-assistant.io).

## Your Environment
* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`
inlets/inlets-operator:0.6.3

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:
[k3s v1.17.2+k3s1](https://github.com/rancher/k3s/releases/tag/v1.17.2%2Bk3s1)

* Kubernetes version `kubectl version`:
v1.17.2

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian Buster Lite (Raspberry Pi 4)

* Cloud provisioner: (DigitalOcean.com / Packet.com / etc)
DigitalOcean.com
